# Generated by Django 4.0.6 on 2022-12-02 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerBio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=155)),
                ('last_name', models.CharField(max_length=155)),
                ('main_position', models.CharField(blank=True, max_length=155, null=True)),
                ('nationality', models.CharField(blank=True, max_length=155, null=True)),
                ('current_club', models.CharField(blank=True, max_length=155, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('b_day', models.DateField()),
                ('pref_foot', models.CharField(choices=[('left', 'left'), ('right', 'right'), ('both', 'both')], max_length=99)),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SeasonStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=9, null=True)),
                ('club', models.CharField(max_length=155)),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('impacting_goals', models.IntegerField(default=0)),
                ('impacting_assists', models.IntegerField(default=0)),
                ('matches', models.IntegerField(default=0)),
                ('minutes', models.IntegerField(default=0)),
                ('yellow_cards', models.IntegerField(default=0)),
                ('red_cards', models.IntegerField(default=0)),
                ('own_goals', models.IntegerField(default=0)),
                ('lost_goals', models.IntegerField(default=0)),
                ('clean_matches', models.IntegerField(default=0)),
                ('on_the_game_sheet_perc', models.IntegerField(default=0)),
                ('first_squad_perc', models.IntegerField(default=0)),
                ('substitute', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('losts', models.IntegerField(default=0)),
                ('win_impact_perc', models.IntegerField(default=0)),
                ('draw_impact_perc', models.IntegerField(default=0)),
                ('lost_impact_perc', models.IntegerField(default=0)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_science.playerbio')),
            ],
        ),
        migrations.CreateModel(
            name='Trophies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_science.seasonstats')),
            ],
        ),
    ]
