# Generated by Django 4.0.6 on 2022-12-02 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_science', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oponnent_name', models.CharField(max_length=155)),
                ('team_goals_scored', models.IntegerField(default=0)),
                ('team_goals_lost', models.IntegerField(default=0)),
                ('player_goals', models.IntegerField(default=0)),
                ('player_assists', models.IntegerField(default=0)),
                ('player_minutes', models.IntegerField(default=0)),
                ('player_yellow_card', models.BooleanField(default=False)),
                ('player_red_card', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=9, null=True)),
                ('club', models.CharField(max_length=155)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_science.playerbio')),
            ],
        ),
        migrations.RemoveField(
            model_name='trophies',
            name='season',
        ),
        migrations.DeleteModel(
            name='SeasonStats',
        ),
        migrations.DeleteModel(
            name='Trophies',
        ),
        migrations.AddField(
            model_name='match',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_science.season'),
        ),
    ]
