# Generated by Django 4.1.3 on 2022-12-03 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_science', '0002_match_season_remove_trophies_season_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailMatchStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tackles', models.IntegerField(default=0)),
                ('interceptions', models.IntegerField(default=0)),
                ('fouls', models.IntegerField(default=0)),
                ('blocks', models.IntegerField(default=0)),
                ('shots', models.IntegerField(default=0)),
                ('key_passes', models.IntegerField(default=0)),
                ('dribbles', models.IntegerField(default=0)),
                ('fouled', models.IntegerField(default=0)),
                ('offsides', models.IntegerField(default=0)),
                ('passes', models.IntegerField(default=0)),
                ('passes_on_target', models.IntegerField(default=0)),
                ('crosses', models.IntegerField(default=0)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data_science.match')),
            ],
        ),
    ]
