# Generated by Django 4.1.3 on 2022-12-03 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_science', '0003_detailmatchstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailmatchstats',
            name='match',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_science.match'),
        ),
    ]
