# Generated by Django 4.1.3 on 2022-12-03 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_science', '0004_alter_detailmatchstats_match'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailmatchstats',
            old_name='crosses',
            new_name='shots_on_target',
        ),
    ]
