# Generated by Django 4.1.3 on 2022-12-03 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_science', '0005_rename_crosses_detailmatchstats_shots_on_target'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailmatchstats',
            old_name='blocks',
            new_name='dribbled',
        ),
    ]
